### ISSUE TITLE
sysc store with a id value

### ISSUE THREAD

**Issue by crazyrunsnail** [ananddayalan/extjs-by-example-todo#1]
Hi.
When I add a to-do, browser send a post request to server.
But the request bring a stranger id value. like:
`{desc: "Hello", id: "extModel43-1", done: false}`
What happen to sysc method.

**Comment by lucasfontesgaspareto** [comment]
Hi,

This id is relative to the id of the _record/rowmodel_ and is automatically generated by extjs.

In **_ToDoListController.js_** you can find this code snippet:
 `html: '<a class="hidden" href="#"><i taskId="' + record.get('id') + '" class="fa fa-times"></i></a>'`

In this case the `record.get('id')` is the id of the record.
